name: Build and Release Video-Hub-App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_on_windows:
    runs-on: windows-latest

    # 定义全局工作目录，省去每一步都写一遍
    defaults:
      run:
        working-directory: ./Video-Hub-App

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install --force

      - name: Build Electron App (EXE)
        run: |
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Video-Hub-App-Exe
          # 注意：这里的路径是相对于根目录的，如果打包输出也在子文件夹，需要对应修改
          path: Video-Hub-App/dist/*.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Video-Hub-App/dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
